<a href="https://colab.research.google.com/github/varadmahatme/TASKS-ML-in-Python/blob/main/TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q 1)
Given an array of integers nums and an integer target, return indices of the two numbers such that
they add up to target. You may assume that each input would have exactly one solution, and you
may not use the same element twice. You can return the answer in any order.

Sample1:
Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].
Sample2:
Input: nums = [3,2,4], target = 6
Output: [1,2]

In [ ]:
																																			# creating an empty list
list = []
list1 = []
																																			# number of elements as input
n = int(input("Enter number of elements : "))
target = int(input("enter the target number")) 												#input the target number
print("enter the",n, "elements")
																													
for i in range(0, n):																									# iterating till the range
	ele = int(input())

	list.append(ele) 																										# adding the element
	
print("entered list is \n",list)

for i in range(len(list)):                     												#outer i loop till length of list                     
    for j in range(i+1, len(list)):						 												#inner j loop from i+1 till length of list
        if list[i]+list[j] == target:																	#check condition if numbers add upto target	
            list1.append(i);list1.append(j);print("output \n",list1)	#print the index of combination
			

Enter number of elements : 3
enter the target number6
enter the 3 elements
3
2
4
entered list is 
 [3, 2, 4]
output 
 [1, 2]


In [ ]:

target = int(input("enter the target number")) #input the target number
for i in range(len(list)):                     #outer i loop till length of list                     
    for j in range(i+1, len(list)):            
        if list[i]+list[j] == target:
            print(list[i], list[j])

enter the target number5
1 4
2 3


(Q 2)
Write a program that takes an unsigned integer and returns the number of '1' bits it has (also known
as the Hamming weight).
Sample1:
Input: n = 00000000000000000000000000001011
Output: 3
Explanation: The input binary string 00000000000000000000000000001011 has a total of three '1'
bits.
Sample2:
Input: n = 11111111111111111111111111111101
Output: 31
Explanation: The input binary string 11111111111111111111111111111101 has a total of thirty one
'1' bits.

In [ ]:
n = int(input("Enter the binary number"))                 #enter the binary number                                                
n = str(n)                                                #typecast to string

count = 0                                                 #initialize the count to 0
for i in n:                                               #start for loop in string n
 if i == "1":                                             #check condition if 1 is encountered
   count+=1                                               #increment counter
print("output: ",count)                                   #print the count


Enter the binary number11111111111111111111111111111101
output:  31


for i in range(len(list)):
    num = target-list[i]
    for j in range(i+1, len(list)):
        if list[j] == num:
            print (list[i], list[j])
PSEUDO code
for i going till length of list
target=num +list OR simply num = target - list[i]
  for j going from i+1 to length of list
  if the list[j] element is equal to the num 
    then print the elements

In [ ]:
import re

python_file = 'file.py'
work_file = None

basic_conversion_rules = {"for": "FOR", "=": "TO", "if": "IF", "==": "EQUALS", "while": "WHILE", "until": "UNTIL", "import": "IMPORT", "class": "DEFINE CLASS", "def": "DEFINE FUNCTION", "else:": "ELSE:", "elif": "ELSEIF", "except:": "EXCEPT:", "try:": "TRY:", "pass": "PASS", "in": "IN"}
prefix_conversion_rules = {"=": "SET ", "#F": "CALL "}
advanced_conversion_rules = {"print": "OUTPUT", "return": "RETURN", "input": "INPUT"}

def f2list(to_list):
    return to_list.readlines()

def l2pseudo(to_pseudo):
    for line in to_pseudo:
        line_index = to_pseudo.index(line)
        line = str(line)
        line = re.split(r'(\s+)', line)
        for key, value in prefix_conversion_rules.items():
            if key in line:
                if not str(line[0]) == '':
                    line[0] = value + line[0]
                else:
                    line[2] = value + line[2]
        for key, value in basic_conversion_rules.items():
            for word in line:
                if key == str(word):
                    line[line.index(word)] = value
        for key, value in advanced_conversion_rules.items():
            for word in line:
                line[line.index(word)] = word.replace(key, value)
        for key, value in prefix_conversion_rules.items():
            for word in line:
                if word == key:
                    del line[line.index(word)]
        to_pseudo[line_index]= "".join(line)
    return(to_pseudo)

def p2file(to_file):
    file = open(python_file + '_pseudo.txt', 'w')
    for line in to_file:
        print(line, file=file)

def main():
    main_file = open(python_file, 'r+')
    work_file = f2list(main_file)
    work_file = l2pseudo(work_file)
    p2file(work_file)
    



In [ ]:
#PSEUDO CODE			

''' 																			
list = []                                                 # creating two empty lists
list1 = []
																													# number of elements as input
n = input("Enter number of elements : ")
target = input("enter the target number")				        	#input the target number
print("enter the",n, "elements")


																													
for i going from 0 to n-1																	# iterating till the range
	ele = input int_value

	append(ele) 																			    	# adding the element to list
	
print(list)

for i going from (0 to len(list))                     		#outer i loop till length of list                     
    for j going from(i+1 to len(list))						 				#inner j loop from i+1 till length of list
        if list[i]+list[j] == target											#check condition if numbers add upto target	
            append(i)                                   	#append to list
            append(j)
            '''

In [ ]:
#PSEUDO CODE
'''
n = input("Enter the int binary number")               #enter the binary number                                                
n = str(n)                                             #typecast to string

count = 0                                              #initialize the count to 0
for i going through string n                           #start for loop in string n
 if i == "1":                                          #check condition if 1 is encountered
   count=count+1                                       #increment counter
print("output: ",count)                                #print the count

'''

TASK 2

In [ ]:
import numpy as np
list_1=[1,2,3,4]
x=np.array(list_1) 
print(x)

[1 2 3 4]


In [ ]:
import numpy as np
list_1=[-1,2,3,4,5,6,'HELLO WORLD',0,None] 
x=np.array(list_1,dtype=bool) 
print(x)

[ True  True  True  True  True  True  True False False]


In [ ]:
import numpy as np
list_1=np.array([1,2,3,4,5,6,7,8])
list_2=np.where(list_1 < 30,list_1+10,list_1)
print(list_2)

[11 12 13 14 15 16 17 18]


In [ ]:
import numpy as np
x=[1,2,3,4,5,6,7,8,9]
y=np.array(x)
op=y.reshape(3,3)
print(op)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
np.vstack((x,y))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
import numpy as np
x=np.array([2,4,6,8,10])
z=np.repeat(x,3)
print(z)

[ 2  2  2  4  4  4  6  6  6  8  8  8 10 10 10]


In [ ]:
import numpy as np
x=np.array([2,3,1,4,6,26,56,7]) 
y=np.array([2,370,2,3,26,9,10,11]) 
np.intersect1d(x,y)

array([ 2,  3, 26])

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([2,4,6,8,10])
np.setdiff1d(x,y)

array([1, 3, 5])

In [ ]:
import numpy as np
x=np.arange(20)
print(x)
np.where((x>=5) & (x<10))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(array([5, 6, 7, 8, 9]),)

In [ ]:
import numpy as np
e=np.random.randint(low=5, high=10,size=(2,2)) 
print(e)

[[6 6]
 [6 7]]


In [ ]:
import numpy as np 
x=np.array([2,5,6,8,11,13,14])
a=np.mean(x)
b=np.median(x)
c=np.std(x)
print(a)
print(b)
print(c)

8.428571428571429
8.0
4.10077145554495


In [ ]:
import numpy as np 
x=np.array([2,4,5,7,8,9,1,2,3]) 
y=(x-np.min(x))/(np.max(x)-np.min(x)) 
print(y)

[0.125 0.375 0.5   0.75  0.875 1.    0.    0.125 0.25 ]


In [ ]:
 import numpy as np 
 x=np.array([2,np.nan,4,6,np.nan,10]) 
 print(np.isnan(x))

[False  True False False  True False]


In [ ]:
import numpy as np 
x=np.array([2,np.nan,4,6,np.nan,10])  
y=np.nan_to_num(x)
print(y)

[ 2.  0.  4.  6.  0. 10.]


In [ ]:
# Import the iris dataset keeping the text intact.
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt (url, delimiter=',', dtype='object')
#=› to retain the species, a text field, set dtype to object
# if set type=None, 1d array of tuples would have been returned.
names = ('sepallength*, "sepalwidth', 'petallength', 'petalwidth', 'species')
# print the first 3 rows
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [ ]:
# LAB TASK 3 PRACTICE

In [2]:
pip install imblearn

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
from imblearn.over_sampling import SMOTE

In [4]:
df  = pd.read_csv('cuisines.csv')

In [5]:
df.head()

Unnamed: 0 cuisine  almond  angelica  anise  anise_seed  apple  \
0          65  indian       0         0      0           0      0   
1          66  indian       1         0      0           0      0   
2          67  indian       0         0      0           0      0   
3          68  indian       0         0      0           0      0   
4          69  indian       0         0      0           0      0   

   apple_brandy  apricot  armagnac  ...  whiskey  white_bread  white_wine  \
0             0        0         0  ...        0            0           0   
1             0        0         0  ...        0            0           0   
2             0        0         0  ...        0            0           0   
3             0        0         0  ...        0            0           0   
4             0        0         0  ...        0            0           0   

   whole_grain_wheat_flour  wine  wood  yam  yeast  yogurt  zucchini  
0                        0     0     0    0      0       0         0  
1                        0     0     0    0      0       0         0  
2                        0     0     0    0      0       0         0  
3                        0     0     0    0      0       0         0  
4                        0     0     0    0      0       1         0  

[5 rows x 385 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2448 entries, 0 to 2447
Columns: 385 entries, Unnamed: 0 to zucchini
dtypes: int64(384), object(1)
memory usage: 7.2+ MB


In [8]:
df.cuisine.value_counts()

korean      799
indian      598
chinese     442
japanese    320
thai        289
Name: cuisine, dtype: int64